package cn.com.easytaxi.ui.bean;

import cn.com.easytaxi.platform.service.CacheBean;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MSG_BEAN.
 */
public class MsgBean extends CacheBean implements java.io.Serializable {

	/**
	 * @Fields serialVersionUID : TODO
	 */
	private static final long serialVersionUID = 1L;

	@SerializedName("mark")
	private Boolean read;

	@SerializedName("msg")
	private String body;

	@SerializedName("createTime")
	private java.util.Date date;

	/**
	 * 1.系统通知 2.自定义消息通知
	 */
	private Integer msgType;

	/**
	 * 1=公告 2=推荐 3=服务 4=新闻 5=恭喜 6=验证系统
	 */
	private Integer msgSubType;

	@SerializedName("show")
	private Integer isShow;

	@SerializedName("TTS")
	private Integer isTTS;

	private String url;

	public MsgBean() {
	}

	public MsgBean(Long id) {
		setCacheId(id);
	}

	public MsgBean(Long id, String body, java.util.Date date, Integer msgType, Integer msgSubType, Integer isShow, Integer isTTS, String url, Boolean read) {
		setCacheId(id);
		this.body = body;
		this.date = date;
		this.msgType = msgType;
		this.msgSubType = msgSubType;
		this.isShow = isShow;
		this.isTTS = isTTS;
		this.url = url;
		this.read = read;
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public java.util.Date getDate() {
		return date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public Integer getMsgType() {
		return msgType;
	}

	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	public Integer getMsgSubType() {
		return msgSubType;
	}

	public void setMsgSubType(Integer msgSubType) {
		this.msgSubType = msgSubType;
	}

	public Integer getIsShow() {
		return isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public Integer getIsTTS() {
		return isTTS;
	}

	public void setIsTTS(Integer isTTS) {
		this.isTTS = isTTS;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Boolean getRead() {
		if (read == null) {
			read = false;
		}
		return read;
	}

	public void setRead(Boolean read) {
		this.read = read;
	}

}
