package cn.com.easytaxi.taxi.bean;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import cn.com.easytaxi.book.BookBean;
import cn.com.easytaxi.ui.bean.MsgBean;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgBeanDaoConfig;
    private final DaoConfig bookBeanDaoConfig;

    private final MsgBeanDao msgBeanDao;
    private final BookBeanDao bookBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgBeanDaoConfig = daoConfigMap.get(MsgBeanDao.class).clone();
        msgBeanDaoConfig.initIdentityScope(type);

        bookBeanDaoConfig = daoConfigMap.get(BookBeanDao.class).clone();
        bookBeanDaoConfig.initIdentityScope(type);

        msgBeanDao = new MsgBeanDao(msgBeanDaoConfig, this);
        bookBeanDao = new BookBeanDao(bookBeanDaoConfig, this);

        registerDao(MsgBean.class, msgBeanDao);
        registerDao(BookBean.class, bookBeanDao);
    }
    
    public void clear() {
        msgBeanDaoConfig.getIdentityScope().clear();
        bookBeanDaoConfig.getIdentityScope().clear();
    }

    public MsgBeanDao getMsgBeanDao() {
        return msgBeanDao;
    }

    public BookBeanDao getBookBeanDao() {
        return bookBeanDao;
    }

}
